name: Renew AppStore Provisioning Profile

on:
  workflow_dispatch:

jobs:
  renew:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true

      - name: Install dependencies
        run: bundle install

      - name: Renew App Store profile (via Fastfile lane)
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}

          # Match-Secrets repo'ya yazabilmek için
          GH_PAT: ${{ secrets.GH_PAT }}
          GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}

          # Fastfile'daki isimlerle aynı olmalı
          TEAMID: ${{ secrets.TEAMID }}
          FASTLANE_KEY_ID: ${{ secrets.FASTLANE_KEY_ID }}
          FASTLANE_ISSUER_ID: ${{ secrets.FASTLANE_ISSUER_ID }}
          FASTLANE_KEY: ${{ secrets.FASTLANE_KEY }}
        run: |
          bundle exec fastlane renew_match_appstore
